#
# Copyright (c) 2012 by Pawel Tomulik
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE

import SCons.Util

Import('env')

dbenv = env.Clone(['docbook'], DOCBOOK_PREFER_XSLTPROC = True)
dbenv.Append(DOCBOOK_XSLTPROCFLAGS = [SCons.Util.CLVar('--xinclude')])

manual_html_src = ['manual.xml']
manual_html_tgt = ['manual.html']
#manual_pdf_tgt = 'manual.pdf'

html_xsl = dbenv.arg2nodes('html.xsl')
#pdf_xsl = dbenv.arg2nodes('pdf.xsl')
manual_html = dbenv.DocbookHtml(manual_html_tgt, manual_html_src, xsl = html_xsl)
#manual_pdf = dbenv.DocbookPdf(manual_pdf_tgt, manual_html_src, xsl = pdf_xsl)

dbenv.Ignore('.', manual_html)
#dbenv.Ignore('.', manual_pdf)
dbenv.AlwaysBuild(dbenv.Alias('user-doc', manual_html))
#dbenv.AlwaysBuild(dbenv.Alias('user-doc', manual_pdf))
